
// 
// Convert individual pieces to their images
// 

type StringKeyStringValue = {
    [key: string] : string
}

export const variableNamesToURLPath: StringKeyStringValue = {

    // White pawns and promotions

    "whitePawnOne": "white_pawn.png",
    "whiteOnePromotionQueen": "white_queen.png",
    "whiteOnePromotionRook": "white_rook.png",
    "whiteOnePromotionKnight": "white_knight.png",
    "whiteOnePromotionBishop": "white_bishop.png",
    "whitePawnTwo": "white_pawn.png",
    "whiteTwoPromotionQueen": "white_queen.png",
    "whiteTwoPromotionRook": "white_rook.png",
    "whiteTwoPromotionKnight": "white_knight.png",
    "whiteTwoPromotionBishop": "white_bishop.png",
    "whitePawnThree": "white_pawn.png",
    "whiteThreePromotionQueen": "white_queen.png",
    "whiteThreePromotionRook": "white_rook.png",
    "whiteThreePromotionKnight": "white_knight.png",
    "whiteThreePromotionBishop": "white_bishop.png",
    "whitePawnFour": "white_pawn.png",
    "whiteFourPromotionQueen": "white_queen.png",
    "whiteFourPromotionRook": "white_rook.png",
    "whiteFourPromotionKnight": "white_knight.png",
    "whiteFourPromotionBishop": "white_bishop.png",
    "whitePawnFive": "white_pawn.png",
    "whiteFivePromotionQueen": "white_queen.png",
    "whiteFivePromotionRook": "white_rook.png",
    "whiteFivePromotionKnight": "white_knight.png",
    "whiteFivePromotionBishop": "white_bishop.png",
    "whitePawnSix": "white_pawn.png",
    "whiteSixPromotionQueen": "white_queen.png",
    "whiteSixPromotionRook": "white_rook.png",
    "whiteSixPromotionKnight": "white_knight.png",
    "whiteSixPromotionBishop": "white_bishop.png",
    "whitePawnSeven": "white_pawn.png",
    "whiteSevenPromotionQueen": "white_queen.png",
    "whiteSevenPromotionRook": "white_rook.png",
    "whiteSevenPromotionKnight": "white_knight.png",
    "whiteSevenPromotionBishop": "white_bishop.png",
    "whitePawnEight": "white_pawn.png",
    "whiteEightPromotionQueen": "white_queen.png",
    "whiteEightPromotionRook": "white_rook.png",
    "whiteEightPromotionKnight": "white_knight.png",
    "whiteEightPromotionBishop": "white_bishop.png",
    
    // White majors

    "whiteRookOne": "white_rook.png",
    "whiteRookTwo": "white_rook.png",
    "whiteKnightOne": "white_knight.png",
    "whiteKnightTwo": "white_knight.png",
    "whiteBishopOne": "white_bishop.png",
    "whiteBishopTwo": "white_bishop.png",
    "whiteQueen": "white_queen.png",
    "whiteKing": "white_king.png",

    // Black pawns and promotions

    "blackPawnOne": "black_pawn.png",
    "blackOnePromotionQueen": "black_queen.png",
    "blackOnePromotionRook": "black_rook.png",
    "blackOnePromotionKnight": "black_knight.png",
    "blackOnePromotionBishop": "black_bishop.png",
    "blackPawnTwo": "black_pawn.png",
    "blackTwoPromotionQueen": "black_queen.png",
    "blackTwoPromotionRook": "black_rook.png",
    "blackTwoPromotionKnight": "black_knight.png",
    "blackTwoPromotionBishop": "black_bishop.png",
    "blackPawnThree": "black_pawn.png",
    "blackThreePromotionQueen": "black_queen.png",
    "blackThreePromotionRook": "black_rook.png",
    "blackThreePromotionKnight": "black_knight.png",
    "blackThreePromotionBishop": "black_bishop.png",
    "blackPawnFour": "black_pawn.png",
    "blackFourPromotionQueen": "black_queen.png",
    "blackFourPromotionRook": "black_rook.png",
    "blackFourPromotionKnight": "black_knight.png",
    "blackFourPromotionBishop": "black_bishop.png",
    "blackPawnFive": "black_pawn.png",
    "blackFivePromotionQueen": "black_queen.png",
    "blackFivePromotionRook": "black_rook.png",
    "blackFivePromotionKnight": "black_knight.png",
    "blackFivePromotionBishop": "black_bishop.png",
    "blackPawnSix": "black_pawn.png",
    "blackSixPromotionQueen": "black_queen.png",
    "blackSixPromotionRook": "black_rook.png",
    "blackSixPromotionKnight": "black_knight.png",
    "blackSixPromotionBishop": "black_bishop.png",
    "blackPawnSeven": "black_pawn.png",
    "blackSevenPromotionQueen": "black_queen.png",
    "blackSevenPromotionRook": "black_rook.png",
    "blackSevenPromotionKnight": "black_knight.png",
    "blackSevenPromotionBishop": "black_bishop.png",
    "blackPawnEight": "black_pawn.png",
    "blackEightPromotionQueen": "black_queen.png",
    "blackEightPromotionRook": "black_rook.png",
    "blackEightPromotionKnight": "black_knight.png",
    "blackEightPromotionBishop": "black_bishop.png",

    // Black Majors

    "blackRookOne": "black_rook.png",
    "blackRookTwo": "black_rook.png",
    "blackKnightOne": "black_knight.png",
    "blackKnightTwo": "black_knight.png",
    "blackBishopOne": "black_bishop.png",
    "blackBishopTwo": "black_bishop.png",
    "blackQueen": "black_queen.png",
    "blackKing": "black_king.png"
}

// 
// Convert individual pieces to their piece type for corresponsing movement rules 
//

export const variableNamesToPieceType: StringKeyStringValue = {
    "whitePawnOne": "pawn",
    "whiteOnePromotionQueen" : "queen",
    "whiteOnePromotionRook": "rook",
    "whiteOnePromotionKnight": "knight",
    "whiteOnePromotionBishop": "bishop",
    "whitePawnTwo": "pawn",
    "whiteTwoPromotionQueen" : "queen",
    "whiteTwoPromotionRook": "rook",
    "whiteTwoPromotionKnight": "knight",
    "whiteTwoPromotionBishop": "bishop",
    "whitePawnThree": "pawn",
    "whiteThreePromotionQueen" : "queen",
    "whiteThreePromotionRook": "rook",
    "whiteThreePromotionKnight": "knight",
    "whiteThreePromotionBishop": "bishop",
    "whitePawnFour": "pawn",
    "whiteFourPromotionQueen" : "queen",
    "whiteFourPromotionRook": "rook",
    "whiteFourPromotionKnight": "knight",
    "whiteFourPromotionBishop": "bishop",
    "whitePawnFive": "pawn",
    "whiteFivePromotionQueen" : "queen",
    "whiteFivePromotionRook": "rook",
    "whiteFivePromotionKnight": "knight",
    "whiteFivePromotionBishop": "bishop",
    "whitePawnSix": "pawn",
    "whiteSixPromotionQueen" : "queen",
    "whiteSixPromotionRook": "rook",
    "whiteSixPromotionKnight": "knight",
    "whiteSixPromotionBishop": "bishop",
    "whitePawnSeven": "pawn",
    "whiteSevenPromotionQueen" : "queen",
    "whiteSevenPromotionRook": "rook",
    "whiteSevenPromotionKnight": "knight",
    "whiteSevenPromotionBishop": "bishop",
    "whitePawnEight": "pawn",
    "whiteEightPromotionQueen" : "queen",
    "whiteEightPromotionRook": "rook",
    "whiteEightPromotionKnight": "knight",
    "whiteEightPromotionBishop": "bishop",
    "whiteRookOne": "rook",
    "whiteRookTwo": "rook",
    "whiteKnightOne": "knight",
    "whiteKnightTwo": "knight",
    "whiteBishopOne": "bishop",
    "whiteBishopTwo": "bishop",
    "whiteQueen": "queen",
    "whiteKing": "king",
    "blackPawnOne": "pawn",
    "blackOnePromotionQueen" : "queen",
    "blackOnePromotionRook": "rook",
    "blackOnePromotionKnight": "knight",
    "blackOnePromotionBishop": "bishop",
    "blackPawnTwo": "pawn",
    "blackTwoPromotionQueen" : "queen",
    "blackTwoPromotionRook": "rook",
    "blackTwoPromotionKnight": "knight",
    "blackTwoPromotionBishop": "bishop",
    "blackPawnThree": "pawn",
    "blackThreePromotionQueen" : "queen",
    "blackThreePromotionRook": "rook",
    "blackThreePromotionKnight": "knight",
    "blackThreePromotionBishop": "bishop",
    "blackPawnFour": "pawn",
    "blackFourPromotionQueen" : "queen",
    "blackFourPromotionRook": "rook",
    "blackFourPromotionKnight": "knight",
    "blackFourPromotionBishop": "bishop",
    "blackPawnFive": "pawn",
    "blackFivePromotionQueen" : "queen",
    "blackFivePromotionRook": "rook",
    "blackFivePromotionKnight": "knight",
    "blackFivePromotionBishop": "bishop",
    "blackPawnSix": "pawn",
    "blackSixPromotionQueen" : "queen",
    "blackSixPromotionRook": "rook",
    "blackSixPromotionKnight": "knight",
    "blackSixPromotionBishop": "bishop",
    "blackPawnSeven": "pawn",
    "blackSevenPromotionQueen" : "queen",
    "blackSevenPromotionRook": "rook",
    "blackSevenPromotionKnight": "knight",
    "blackSevenPromotionBishop": "bishop",
    "blackPawnEight": "pawn",
    "blackEightPromotionQueen" : "queen",
    "blackEightPromotionRook": "rook",
    "blackEightPromotionKnight": "knight",
    "blackEightPromotionBishop": "bishop",
    "blackRookOne": "rook",
    "blackRookTwo": "rook",
    "blackKnightOne": "knight",
    "blackKnightTwo": "knight",
    "blackBishopOne": "bishop",
    "blackBishopTwo": "bishop",
    "blackQueen": "queen",
    "blackKing": "king"
}

export const blackPiecesIndexToPieceName: string[] = [
    "blackPawnOne",
    "blackPawnTwo",
    "blackPawnThree",
    "blackPawnFour",
    "blackPawnFive",
    "blackPawnSix",
    "blackPawnSeven",
    "blackPawnEight",
    "blackRookOne",
    "blackRookTwo",
    "blackKnightOne",
    "blackKnightTwo",
    "blackBishopOne",
    "blackBishopTwo",
    "blackQueen",
    "blackKing"
]

type StringKeyNumberValue = {
    [key: string] : number
}

export const pieceTypeToValue: StringKeyNumberValue = {
    "pawn": 1,
    "knight": 3,
    "bishop": 3.2,
    "rook": 5,
    "queen": 9
}