
// All White starting positions
// Includes potential pawn promotions
// export const initialWhitePieces: ChessPieces = {
//     whitePawnOne: "a2",
//     whiteOnePromotionQueen: "a6",
//     whiteOnePromotionRook: "na",
//     whiteOnePromotionKnight: "na",
//     whiteOnePromotionBishop: "na",
//     whitePawnTwo: "b2",
//     whiteTwoPromotionQueen: "na",
//     whiteTwoPromotionRook: "na",
//     whiteTwoPromotionKnight: "na",
//     whiteTwoPromotionBishop: "c4",
//     whitePawnThree: "c2",
//     whiteThreePromotionQueen: "na",
//     whiteThreePromotionRook: "na",
//     whiteThreePromotionKnight: "na",
//     whiteThreePromotionBishop: "na",
//     whitePawnFour: "d2",
//     whiteFourPromotionQueen: "na",
//     whiteFourPromotionRook: "na",
//     whiteFourPromotionKnight: "na",
//     whiteFourPromotionBishop: "na",
//     whitePawnFive: "e2",
//     whiteFivePromotionQueen: "na",
//     whiteFivePromotionRook: "na",
//     whiteFivePromotionKnight: "na",
//     whiteFivePromotionBishop: "na",
//     whitePawnSix: "f2",
//     whiteSixPromotionQueen: "na",
//     whiteSixPromotionRook: "na",
//     whiteSixPromotionKnight: "na",
//     whiteSixPromotionBishop: "na",
//     whitePawnSeven: "g2",
//     whiteSevenPromotionQueen: "na",
//     whiteSevenPromotionRook: "na",
//     whiteSevenPromotionKnight: "na",
//     whiteSevenPromotionBishop: "na",
//     whitePawnEight: "h2",
//     whiteEightPromotionQueen: "na",
//     whiteEightPromotionRook: "na",
//     whiteEightPromotionKnight: "na",
//     whiteEightPromotionBishop: "na",
//     whiteRookOne: "a1",
//     whiteRookTwo: "h1",
//     whiteKnightOne: "b1",
//     whiteKnightTwo: "g1",
//     whiteBishopOne: "c1",
//     whiteBishopTwo: "f1",
//     whiteQueen: "d1",
//     whiteKing: "e1",
// };

// export const initialBlackPieces: ChessPieces = {
//     blackPawnOne: "a7",
//     blackOnePromotionQueen: "na",
//     blackOnePromotionRook: "f5",
//     blackOnePromotionKnight: "g5",
//     blackOnePromotionBishop: "na",
//     blackPawnTwo: "b7",
//     blackTwoPromotionQueen: "na",
//     blackTwoPromotionRook: "na",
//     blackTwoPromotionKnight: "na",
//     blackTwoPromotionBishop: "na",
//     blackPawnThree: "c7",
//     blackThreePromotionQueen: "na",
//     blackThreePromotionRook: "na",
//     blackThreePromotionKnight: "na",
//     blackThreePromotionBishop: "na",
//     blackPawnFour: "d7",
//     blackFourPromotionQueen: "na",
//     blackFourPromotionRook: "na",
//     blackFourPromotionKnight: "na",
//     blackFourPromotionBishop: "na",
//     blackPawnFive: "e7",
//     blackFivePromotionQueen: "na",
//     blackFivePromotionRook: "na",
//     blackFivePromotionKnight: "na",
//     blackFivePromotionBishop: "na",
//     blackPawnSix: "f7",
//     blackSixPromotionQueen: "na",
//     blackSixPromotionRook: "na",
//     blackSixPromotionKnight: "na",
//     blackSixPromotionBishop: "na",
//     blackPawnSeven: "g7",
//     blackSevenPromotionQueen: "na",
//     blackSevenPromotionRook: "na",
//     blackSevenPromotionKnight: "na",
//     blackSevenPromotionBishop: "na",
//     blackPawnEight: "h7",
//     blackEightPromotionQueen: "na",
//     blackEightPromotionRook: "na",
//     blackEightPromotionKnight: "na",
//     blackEightPromotionBishop: "na",
//     blackRookOne: "a8",
//     blackRookTwo: "h8",
//     blackKnightOne: "b8",
//     blackKnightTwo: "g8",
//     blackBishopOne: "c8",
//     blackBishopTwo: "f8",
//     blackQueen: "d8",
//     blackKing: "e8",
// }

type ChessPieces = {
    [key: string] : string
}

export const initialWhitePieces: ChessPieces = {
    whitePawnOne: "a7",
    whiteOnePromotionQueen: "na",
    whiteOnePromotionRook: "na",
    whiteOnePromotionKnight: "na",
    whiteOnePromotionBishop: "na",
    whitePawnTwo: "b7",
    whiteTwoPromotionQueen: "na",
    whiteTwoPromotionRook: "na",
    whiteTwoPromotionKnight: "na",
    whiteTwoPromotionBishop: "na",
    whitePawnThree: "c2",
    whiteThreePromotionQueen: "na",
    whiteThreePromotionRook: "na",
    whiteThreePromotionKnight: "na",
    whiteThreePromotionBishop: "na",
    whitePawnFour: "d2",
    whiteFourPromotionQueen: "na",
    whiteFourPromotionRook: "na",
    whiteFourPromotionKnight: "na",
    whiteFourPromotionBishop: "na",
    whitePawnFive: "e2",
    whiteFivePromotionQueen: "na",
    whiteFivePromotionRook: "na",
    whiteFivePromotionKnight: "na",
    whiteFivePromotionBishop: "na",
    whitePawnSix: "na",
    whiteSixPromotionQueen: "na",
    whiteSixPromotionRook: "na",
    whiteSixPromotionKnight: "na",
    whiteSixPromotionBishop: "na",
    whitePawnSeven: "na",
    whiteSevenPromotionQueen: "na",
    whiteSevenPromotionRook: "na",
    whiteSevenPromotionKnight: "na",
    whiteSevenPromotionBishop: "na",
    whitePawnEight: "na",
    whiteEightPromotionQueen: "na",
    whiteEightPromotionRook: "na",
    whiteEightPromotionKnight: "na",
    whiteEightPromotionBishop: "na",
    whiteRookOne: "a1",
    whiteRookTwo: "na",
    whiteKnightOne: "b1",
    whiteKnightTwo: "na",
    whiteBishopOne: "c1",
    whiteBishopTwo: "na",
    whiteQueen: "d1",
    whiteKing: "e1",
};

export const initialBlackPieces: ChessPieces = {
    blackPawnOne: "na",
    blackOnePromotionQueen: "na",
    blackOnePromotionRook: "na",
    blackOnePromotionKnight: "na",
    blackOnePromotionBishop: "na",
    blackPawnTwo: "na",
    blackTwoPromotionQueen: "na",
    blackTwoPromotionRook: "na",
    blackTwoPromotionKnight: "na",
    blackTwoPromotionBishop: "na",
    blackPawnThree: "na",
    blackThreePromotionQueen: "na",
    blackThreePromotionRook: "na",
    blackThreePromotionKnight: "na",
    blackThreePromotionBishop: "na",
    blackPawnFour: "d7",
    blackFourPromotionQueen: "na",
    blackFourPromotionRook: "na",
    blackFourPromotionKnight: "na",
    blackFourPromotionBishop: "na",
    blackPawnFive: "e7",
    blackFivePromotionQueen: "na",
    blackFivePromotionRook: "na",
    blackFivePromotionKnight: "na",
    blackFivePromotionBishop: "na",
    blackPawnSix: "f7",
    blackSixPromotionQueen: "na",
    blackSixPromotionRook: "na",
    blackSixPromotionKnight: "na",
    blackSixPromotionBishop: "na",
    blackPawnSeven: "g2",
    blackSevenPromotionQueen: "na",
    blackSevenPromotionRook: "na",
    blackSevenPromotionKnight: "na",
    blackSevenPromotionBishop: "na",
    blackPawnEight: "h2",
    blackEightPromotionQueen: "na",
    blackEightPromotionRook: "na",
    blackEightPromotionKnight: "na",
    blackEightPromotionBishop: "na",
    blackRookOne: "na",
    blackRookTwo: "h8",
    blackKnightOne: "na",
    blackKnightTwo: "g8",
    blackBishopOne: "na",
    blackBishopTwo: "f8",
    blackQueen: "d8",
    blackKing: "e8",
}